#声明服务路由
spring:
  cloud:
    gateway:
      routes:
          #路由名称:不重复即可
        - id: provider-routes
            #lb:从eureka中获取服务
          uri: lb://portal-web
          #谓语:url包含provider
          predicates:
            - Path=/portal/**
          filters:
            # redis限流 ， filter名称必须是RequestRateLimiter
            - name: RequestRateLimiter
              args:
                # 使用SpEL名称引用Bean，与上面新建的RateLimiterConfig类中的bean的name相同
                key-resolver: '#{@remoteAddrKeyResolver}'
                # 每秒最大访问次数
                redis-rate-limiter.replenishRate: 5
                # 令牌桶最大容量
                redis-rate-limiter.burstCapacity: 10
          # 进行token过滤
           # - TokenAuthenticationFilter
          #- PrefixPath=/mypath  是在请求地址上追加，- StripPrefix=2 是去掉匹配中的地址
            - StripPrefix=1
            ## 熔断降级配置
#            - name: Hystrix
#              args:
#                name: default
#                fallbackUri: 'forward:/defaultfallback'


  redis:
    host: localhost
    port: 6379
    database: 0